### ISSUE TITLE
Nothing in the "Main Window" after "Send to ExtendedMacro"

### ISSUE THREAD

**Issue by unkown571** [FrUh/ExtendedMacro#4]
1. burpsuite 1.7.26 with jdk 1.8.0_102
Extender -> Extensions -> ExtendedMacro can be Loaded, but does not work:
1) Select one item from HTTP History, and then right click choose "Send to ExtendedMacro",
2) the "Extended Macro" tab is changed to orange color, but no message was there, nothing,  empty. i.e. the item was not sent to "Main Window".

I tried another version of jdk, it's even cannot be loaded.
2. burpsuite 1.7.26 with jdk_1.7.0_17
Extender -> Extensions -> ExtendedMacro,  can not be loaded with error message:
java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:266)
	at burp.sue.a(Unknown Source)
	at burp.sue.<init>(Unknown Source)
	at burp.mn.a(Unknown Source)
	at burp.ooh.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:722)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by fruh** [comment]
Hi, the problem is, that you are running burpsuite (probably bundle) with Java 1.7.0_17 what is version 51, with Java 1.8.0 (version 52) it should work,  i am using 1.8.0_162 amd it works.

Could you please send me stacktrace from java 1.8 run?

**Comment by unkown571** [comment]
Sorry, I dont know how to extract "stacktrace" information, but I tried jdk 1.8.0_162, the problem still exist.

OS:   Windows 7 64 bit
JDK:  java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

BurpSuite v1.7.26  was downloaded  from https://sourceforge.net/projects/burpunlimited/files/

Oh, the ExtendedMacro was installed in BApp Store: Extender ->BApp Store -> ExtendedMacro -> Install
version 0.0.5
Filename  bapps\33839d04fdaa4e3b80292fbed115db13\dist\extendedmacro.jar

**Comment by fruh** [comment]
oh man :(...you should by one license, its quite cheap ;) https://portswigger.net/burp

It works with java 1.8 without problems.
